services:
  api:
    environment:
      NODE_ENV: PROD
      CHATFLUX_ENV: Staging
      NEW_RELIC_APP_NAME: "Staging Evolution API"
      LOG_LEVEL: "DEBUG"
      CACHE_REDIS_ENABLED: "true"
      CACHE_LOCAL_ENABLED: "false"
